### ISSUE TITLE
templates

### ISSUE THREAD

**Issue by akoenig** [danielstjules/pjs#3]
@danielstjules, what do you think of a template feature? Something where you can define CommonJS-style modules for repeating filter/map/reduce tasks, like:

`~/.config/pjs/templates/debug-log.js`

```javascript
module.exports = function template (pjs) {
    return pjs
        .filter(function (item) {
            return !!~item.indexOf('DEBUG');
        })
        .map(function (item) {
            return "Found debug entry: " + item;
        });

        // omitting "reduce" here ...
};
```

could be used in `pjs` as:

```sh
tail -f ~/logs/*.log | pjs -t debug-log
```

**Comment by danielstjules** [comment]
Interesting idea! Do you think there's major benefits over just letting people define their own alias?

``` bash
alias debug="pjs -e -f \"!!~$.indexOf('DEBUG')\" -m '\"Found debug entry: \" + $'"
```

**Comment by akoenig** [comment]
They are easier to read and extendable with the help of the npm ecosystem :) A template author could use external modules for doing crazy manipulations (for example).

**Comment by danielstjules** [comment]
Hm, I like that idea. Though I don't think I'd have pjs ever run an `install` step. That would mean either:

* Keep a `node_modules` in the templates dir, and parse each template for `require` statements, installing modules as necessary. This isn't ideal as it doesn't handle versioning.

* Require some sort of `package.json` somewhere from which the user must run `npm install`, and load from there. This isn't great, as it imposes some messy organization/configuration.

* Or require that templates themselves be modules. Then they could be installed via `pjs install pjs-template-name`, which would simply run `npm install` in the `.config/pjs` directory. 

I'm undecided as to which solution would be ideal. Of course, the alternative to any of the above would be to let the user manage their own dependencies for their templates, installing them globally under their user just as `pjs` is done.

**Comment by danielstjules** [comment]
@akoenig any thoughts on the above?

**Comment by akoenig** [comment]
Hm, hard to say how to handle this scenario. I think that I tend to installing pjs templates globally (like yeoman generators) which might have the positive effect of creating a new pjs-* ecosystem with useful template modules .. hehe

**Comment by bradparks** [comment]
sounds like a good idea to me as well!

**Comment by danielstjules** [comment]
Closing because I don't think anyone actually uses this project haha Though PRs are certainly welcome.
