### ISSUE TITLE
Include support for Lodash?

### ISSUE THREAD

**Issue by thalesmello** [danielstjules/pjs#5]
Hello.

I was wondering if it would be possible to include support for [lodash](https://lodash.com/). It includes all sorts of useful functions, which I think work great with your command line tool.

I've create a [reference implementation](https://github.com/thalesmello/pjs/blob/master/lib/pjs.js), in which I just required the library.

With it, it's possible to camelize words. For example

```
echo "foo_bar\nbee-bop" | pjs -m '_.camelCase($)'
```

**Comment by danielstjules** [comment]
I'd welcome a PR! Otherwise I can probably get something in master in the next couple days. :)

**Comment by thalesmello** [comment]
I'll send a PR for review later.

I'm experimenting with some syntaxes, such as $$ as a shorthand to chain
lodash operations.

Atenciosamente,
Thales Mello.

**Comment by danielstjules** [comment]
Anything you'd like to mention from your experiments? :)
